### ISSUE TITLE
Failed create Xamarin Forms project

### ISSUE THREAD

**Issue by Janek91** [Plac3hold3r/MvxScaffolding#906]
When I try to create Xamarin Forms project - it throws an error:
```
---------------------------
MvxScaffolding unhandled exception
---------------------------
There was an exception thrown when trying to run MvxScaffolding. Please log an issue on GitHub if the error persists.

Exception Message: Set connectionId threw an exception.
Exception StackTrace:   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)

   at MahApps.Metro.Controls.GlowWindow.InitializeComponent()

   at MahApps.Metro.Controls.GlowWindow..ctor(Window owner, GlowDirection direction)

   at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectOnLoaded(Object sender, RoutedEventArgs routedEventArgs)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)

   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)

   at MS.Internal.LoadedOrUnloadedOperation.DoWork()

   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()

   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)

   at System.Windows.Interop.HwndTarget.OnResize()

   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Inner Exception Message: [A]MahApps.Metro.Controls.Glow cannot be cast to [B]MahApps.Metro.Controls.Glow. Type A originates from 'MahApps.Metro, Version=1.6.5.1, Culture=neutral, PublicKeyToken=null' in the context 'LoadFrom' at location 'c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\eibxuxcf.gui\MahApps.Metro.dll'. Type B originates from 'MahApps.Metro, Version=1.6.5.1, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' in the context 'LoadFrom' at location 'C:\USERS\JANPAWEL\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_ACB3C1E0\EXTENSIONS\QSL0EYGU.WKG\MahApps.Metro.dll'.
Inner Exception StackTrace:   at MahApps.Metro.Controls.GlowWindow.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)

   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
---------------------------
OK   
---------------------------
```

**Comment by Plac3hold3r** [comment]
@Janek91 this seems to be the same issue as #776 and #905 where the assembly is getting loaded from the admin install and not the user install directory. You can delete the extension from the admin extension directory (delete `eibxuxcf.gui`)

```shell
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\eibxuxcf.gui
```

**Comment by Plac3hold3r** [comment]
@Janek91 any luck in implementing the work around?
